### ISSUE TITLE
Loading spatial layers

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/IEK#1]

**Comment by ansell** [comment]
This is a checklist to track the layers assigned with the IEK label in layers-service and their status:

https://github.com/AtlasOfLivingAustralia/layers-service/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3AIEK+

The following are simple layers that can be uploaded quickly due to them being distributed in ESRI Shapefile format and being readily accessible and open licensed:
- [ ] Load Layer - RATSIB Areas (Representative Aboriginal and Torres Straight Islander Body) AtlasOfLivingAustralia/layers-service#71 - Uploaded to spatial-test
- [ ] Load Layer - update Indigenous Protected Areas with 2016 version AtlasOfLivingAustralia/layers-service#61 - Uploaded to spatial-test
- [ ] Load Layer - Native title determination map - update AtlasOfLivingAustralia/layers-service#72 - Uploaded to spatial-test
- [ ] Load Layer - Indigenous Land Use Agreements (ILUA) - update AtlasOfLivingAustralia/layers-service#73 - Uploaded to spatial-test
- [x] Load Layer - Indigenous forest estate AtlasOfLivingAustralia/layers-service#70 - Converted using gdal_translate from ARCGis to ESRI HDR format and uploaded to spatial-test

The ABS datasets below are labelled as Copyright ABS but the ABS has confirmed that all Boundaries that they publish are available under CC-BY:
- [ ] Load layer - ABS Indigenous Areas AtlasOfLivingAustralia/layers-service#81
- [ ] Load layer - ABS Indigenous Locations AtlasOfLivingAustralia/layers-service#81
- [ ] Load layer - ABS Indigenous Regions AtlasOfLivingAustralia/layers-service#81
- [ ] Load layer - ABS Remoteness Area AtlasOfLivingAustralia/layers-service#81
- [ ] Load layer - ABS Census Counts by Indigenous Region - 2006-2011 AtlasOfLivingAustralia/layers-service#81

The following are layers that will each take more time than usual due to them either not being available in GIS formats, or being distributed in a format other than the ESRI Shapefile format that the ALA spatial.ala.org.au supports for uploads:
- [ ] Load Layer - AURIN layers AtlasOfLivingAustralia/layers-service#75
- [ ] Load Layer - language boundaries AtlasOfLivingAustralia/layers-service#69
- [ ] Load Layer - Indigenous population map and locations AtlasOfLivingAustralia/layers-service#74

**Comment by ansell** [comment]
This is just a tracking issue, estimates need to be made on each of the layers themselves, so have removed the estimate from this issue so people don't get confused about how much time layer loading will take.
